#!/usr/bin/env php
<?php

declare(strict_types = 1);

use App\Contracts\Register\RegisterCustomer;

include __DIR__ . '/../vendor/autoload.php';

$publisher = new ToolsPublisher(__DIR__ . '/../.env');

$publisher->sendMessage(
    new RegisterCustomer(
        'qwerty@root.com',
        'login',
        'password',
        'd647f0c5-c74c-425b-b97f-b2fab60a0d23'
    )
);
